version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: karestwww/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    env_file: .env
    image: karestwww/foodgram_frontend  # Качаем с Docker Hub
    command: cp -r /app/result_build/. /frontend_static/
    volumes:
      - static:/frontend_static/

  gateway:
    image: karestwww/foodgram_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/media/
    ports:
      - 7000:80
    depends_on:
      - backend
      - frontend
