# Generated by Django 3.2.3 on 2024-10-16 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ('recipe',), 'verbose_name': 'избранный', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='recipe',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='recipe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='in_shopping_cart', to='recipes.recipe', verbose_name='Рецепт'),
            preserve_default=False,
        ),
    ]
