# Generated by Django 3.2.3 on 2024-10-22 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20241021_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'default_related_name': 'recipes', 'ordering': ('-id',), 'verbose_name': 'рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
